### ISSUE TITLE
Just stumbled upon this, awesome!

### ISSUE THREAD

**Issue by lhr0909** [tychota/shitake#1]
Hey just wanted to swing by and say hi! We have been working on a project using CQRS and exposing gRPC endpoints as well, and found some of these utilities very useful! Just curious on your motivation for this and would love to help out and ship some of the features if you have things planned.

**Comment by tychota** [comment]
Hi,

First thank you 😍Much appreciated. 

> and found some of these utilities very useful! 

That is especially nice to hear, provide I haven't even added a simple readme.

## 🎉 Motivation

I work as an architect at https://www.bam.tech/

I'm currently staff for the frontend part on a dating app that use a lot of CQRS/hexa architecture for the backend.

I then add to estimate and sale a project that would need such an architecture.

I realised that while I, personally, would do it in a set of technology (either akka stream or elixir with commanded), no one in my company would be able to work on it (we are specialist of JS, and we do a bit of php/python).

Thus I create this test project to test nest and standardise some good practices.

It will be updated a bit, documented a bit but won't be use in reality. What will be used will be closed source.

## 🛣Road / star map for this

(probably will be edited as I have surely forgotten a lot)

### Do Next

- [ ] AuthGuard with JWT
- [ ] Unit Test

### Probably just after

- [ ] E2E Test
- [ ] Better linter
- [ ] Task inter microservice: so far with Celery (python) and RabbitMQ
- [ ] Document:
  - Why CQRS? Short term Pro? Short term Cons? Maintainability ? Links to learn more.
  - Why Onion architecture? Short term Pro? Short term Cons? Maintainability ? Links to learn more.
  - Why GRQC? Short term Pro? Short term Cons? Maintainability ? Links to learn more.
  - Why Celery/RabbitMQ? Short term Pro? Short term Cons? Maintainability ? Links to learn more.
  - How to create new µService/Query/Command ? Step by step.

### Possibly in the future

- [ ] Deploying on kubernetes with helm.
- [ ] CI with docker
- [ ] CD (green/blue deployment, https://docs.nestjs.com/recipes/terminus)
- [ ] Improve dev server to auto restart
- [ ] Invest https://www.citusdata.com/ for eventStore scalling and/or snapshot from https://dev.to/kspeakman/event-storage-in-postgres-4dk2
- [ ] analytics with InfluxDB/Graphana

## Unlikely but maybe

- [ ] tracing
- [ ] service mesh
- [ ] a celery like framework base on RabbitMQ

## 👤 About you ? And working together

> Hey just wanted to swing by and say hi! We have been working on a project using CQRS and exposing gRPC endpoints as well, and found some of these utilities very useful! Just curious on your motivation for this and would love to help out and ship some of the features if you have things planned.

Tell me more :)
 
> would love to help out and ship some of the features if you have things 

Would love to have some criticism about the current and upcoming architecture.

If we want to go forward and make it real, we should have real objective for the test site: like a recipe (only about food that fits with shitake mushroom) website with comments, like and so.

WDYT ?
